version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=simple_blog_api
  
  api:
    depends_on:
      - postgres
    build: .
    # dockerfile =Dockerfile.dev  
    image: nikithak/simple-blog-api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=simple_blog_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"